# Generated by Django 2.1.3 on 2018-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255, verbose_name='工作名称')),
                ('creator', models.CharField(default='admin', max_length=100, verbose_name='创建者')),
                ('work_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作',
                'verbose_name_plural': '工作',
            },
        ),
        migrations.CreateModel(
            name='workData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='20150214044', max_length=10, verbose_name='学号')),
                ('work_id', models.CharField(max_length=10, verbose_name='工作id')),
                ('work_content', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '用户提交数据表',
                'verbose_name_plural': '用户提交数据表',
            },
        ),
    ]
