# Generated by Django 2.1.3 on 2018-12-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdata',
            name='student_number',
            field=models.CharField(max_length=10, verbose_name='学号'),
        ),
    ]
